name: hr56_staff
description: HR56 Staff Mobile Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.0
  intl: ^0.17.0
  equatable: ^2.0.3
  logger: ^1.1.0
  get_it: ^7.2.0
  connectivity_plus: ^2.3.0
  flutter_screenutil: ^5.5.1
  auto_route: ^5.0.2
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  file_picker: ^5.2.4
  image_picker: ^0.8.6
  flutter_gen: ^5.2.0
  carousel_slider: ^4.2.1
  pin_code_fields: ^7.4.0
  flutter_dotenv: ^5.1.0
  retrofit: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.2.1
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^3.0.1
  auto_route_generator:
  retrofit_generator:
  build_runner:
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  flutter_native_splash: ^2.2.15

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Bold.otf
        - asset: assets/fonts/ClashDisplay-Semibold.otf
        - asset: assets/fonts/ClashDisplay-Extralight.otf
        - asset: assets/fonts/ClashDisplay-Light.otf
        - asset: assets/fonts/ClashDisplay-Medium.otf
        - asset: assets/fonts/ClashDisplay-Regular.otf
  
